- pluma/pluma-statusbar.c
- pluma/pluma-statusbar.h
- pluma/pluma-window.c
- fixes the large statusbar with GTK3
- remove extra resize-grip code, which is handle by gtk+ itself,
GTK2 builds displays the resize-grip without the extra code.
Since GTK+-3.14 the resize-grip widget is removed.
- the size of the statusbar is now themable
all is based from https://git.gnome.org/browse/gedit/commit/?h=gnome-3-8&id=97ad874a79fd1e937a9f660e4c8fae9d1dcb37fb
and
https://git.gnome.org/browse/gedit/commit/?id=406a5bb2462ee364a4ffd7217e554d08611d97bb
> reduce the size of the statusbar

- plugins/taglist/Makefile.am
fixes https://github.com/mate-desktop/pluma/issues/119
> taglist plugin: don't use timestamps when using gzip

- pluma/pluma-utils.c
when opening a file on some mounted drive (local harddisk, usb flash drive, etc.),
pluma now displays full path to file in the window title. previously it displayed
only the mount name (like "100 GB Volume").
adapted from:
https://git.gnome.org/browse/gedit/commit?id=c59e67e27ea11c6756c7291236338fcf44f24c73
credits to @jsenin for https://github.com/mate-desktop/pluma/pull/108
closes https://github.com/mate-desktop/pluma/pull/108
> window title: display full path to files on mounted drives

- configure.ac
- pluma/pluma-commands-help.c
- about-dialog use GtkAbout instead of MateAbout in this case
- this makes transition to gtk3 more simple
> add a configure option to build pluma with --without-matedesktop

- configure.ac
- plugins/spell/Makefile.am
- plugins/spell/org.mate.pluma.plugins.spell.gschema.xml.in
- plugins/spell/pluma-spell-plugin.c
- plugins/spell/pluma-spell-plugin.h
- plugins/spell/pluma-spell-setup-dialog.ui
- po/POTFILES.in
mate-desktop/pluma#90
(Creating a new pull request here as the previous one was closed when I deleted and recreated cloned branch after some help from @infirit to tidy up my commit)
There are three options for autocheck when a doc is loaded:
Always autocheck, Never autocheck and Remember the autocheck setting for each document
The chosen option is stored in the gsettings schema.
The default setting is to remember by document as this is what Pluma did previously.
> Add a new Configure dialog for the Spell Check plugin.

- plugins/Makefile.am
It was accidentally changed to be installed unconditionally with
"drop support for win32/osx".
> plugins: Fix to install externaltools plugin only with Python

- configure.ac
- plugins/Makefile.am
- plugins/externaltools/Makefile.am
- plugins/externaltools/externaltools.plugin.desktop.in
- plugins/externaltools/tools/__init__.py
- plugins/externaltools/tools/capture.py
- plugins/externaltools/tools/filelookup.py
- plugins/externaltools/tools/functions.py
- plugins/externaltools/tools/library.py
- plugins/externaltools/tools/manager.py
- plugins/externaltools/tools/outputpanel.py
- plugins/externaltools/tools/tools.ui
- plugins/pythonconsole/Makefile.am
- plugins/pythonconsole/pythonconsole.plugin.desktop.in
- plugins/pythonconsole/pythonconsole/__init__.py
- plugins/pythonconsole/pythonconsole/console.py
- plugins/quickopen/Makefile.am
- plugins/quickopen/quickopen.plugin.desktop.in
- plugins/quickopen/quickopen/__init__.py
- plugins/quickopen/quickopen/popup.py
- plugins/quickopen/quickopen/virtualdirs.py
- plugins/quickopen/quickopen/windowhelper.py
- po/POTFILES.in
- po/POTFILES.skip
@raveit65 @XRevan86 @lukefromdc @sc0w
Please test it if you can guys.
You'll need introspection packages for libpeas and Pluma itself, and also Python plugins loader from libpeas. Depending on your distro, the loader might be in the same package as libpeas itself or in a separate one.
Just in case - how to test plugins:
* externaltools:
* press Ctrl-F9 to enable the bottom pane
* select the tab with the gear icon to reveal the shell output window
* use ```Tools -> External Tools``` menu (or use keyboard shortcuts) to run various tools
* use ```Tools -> Manage External Tools...``` menu item to invoke the tools manager dialog
* try adding and removing tools (they should be saved to ```~/.config/pluma/tools/```)
* try changing various settings for the existing tools (code, shortcuts, …
> port Python plugins (except for snippets) to gi and libpeas

- plugins/filebrowser/pluma-file-bookmarks-store.c
The gtk bookmarks file is now in XDG dir, so let's first try there and
otherwise fall back to the old location.
Please test, commit didn't apply clean.
> Support new location of gtk bookmarks file

- pluma/pluma-window.c
This change is needed after https://github.com/mate-desktop/pluma/commit/2b34ed27ac4abde8d70735c008bd214a79b45491
The issue:
1. open file with pluma
2. open the same file with another editor (geany, vim, nano, ... ...)
3. modify and save the file with the other editor
4. go to pluma and see the behavior
Videos:
without the PR:
https://mega.nz/#!Idxz0Rxb!QQ0jKBI5YMW1pd04N9XKWA5G_yOzMySdYpOk_ehjlv4
with the PR:
https://mega.nz/#!xFIBHJJD!hbfgjud_MB-4PggTRQMvFCDtgxY6TCliMhDI-7nPRcg
> enable the abbility to save the document if it was changed externally

- pluma/pluma-window.c
gdk_screen_get_monitor_geometry
gdk_screen_get_monitor_at_window
> gtk 3.22: avoid deprecated gdk_screen_get_monitor... functions:

- pluma/pluma-window.c
to increase/decrease font size
related issue: https://github.com/mate-desktop/pluma/issues/224
in the past I did the PR https://github.com/mate-desktop/pluma/pull/253 , and now it works too with the numeric keypad
> [ctrl] + [+] / [ctrl] + [-] using the numeric keypad

- pluma/pluma-app.c
there is only one screen, this code can be removed
Fixes https://github.com/mate-desktop/pluma/issues/261
> make sure pluma open in the same window of the workspace

- pluma/pluma-view.c
This is the improvement of this two commits:
https://github.com/mate-desktop/pluma/commit/4df44887f4b7547fc9b31d1cb3f61688579fe39b
https://github.com/mate-desktop/pluma/commit/ec438f3d262ef178a898612211335d3c9fa2f4ee
The tests: make sure you can't reproduce the issues #250 and #256
> pluma-view.c: use one static variable instead two to do the same job

- pluma/pluma-commands-search.c
- pluma/pluma-document.c
- pluma/pluma-document.h
- pluma/pluma-utils.c
- pluma/pluma-utils.h
- pluma/pluma-view.c
resolves #254 
Seems to work correct. Some additional tests from @hanaokaiwa are appreciated.
> Fixes for regexp replacement with backreferences (e.g. "\0")

- pluma/pluma-window.c
attempt at fixing that weird regression from https://github.com/mate-desktop/pluma/pull/259#issuecomment-351084165
> pluma-window: have GtkRecentData on stack instead of allocating it

- pluma/pluma-plugins-engine.c
- pluma/pluma-tab.c
and this commit reverts:
https://github.com/mate-desktop/pluma/commit/e81883304c118abc3f8b7198cdc336a9a10f6571
now it isn't needed
@monsta and with this PR, you can revert https://github.com/mate-desktop/pluma/commit/e86397d000d3d307cb425404c74f963c0073b99b and test, the list of recently used files works too!
> put 'peas_engine_enable_loader' in the correct place

- plugins/spell/pluma-spell-setup-dialog.ui
avoid deprecated GtkVBox and GtkButton:use-stock
I noticed the buttons in the ui file: '`Help`', '`Cancel`', and '`OK`', never works without/with the PR
> spell plugin: pluma-spell-setup-dialog.ui: avoid deprecated:

- plugins/docinfo/docinfo.ui
the expected: the same look and behavior like before
> plugins: docinfo.ui: avoid GtkButton:use-stock and GtkImage:stock

- plugins/docinfo/docinfo.ui
and now, there is no deprecations
> docinfo.ui plugin: avoid GtkVBox, GtkHBox, GtkLabel:xpad/ypad & GtkTable

- po/POTFILES.in
A file was missing from translations.
> Fix make distcheck

- plugins/time/pluma-time-dialog.ui
GtkVBox
GtkHBox
GtkLabel:xpad/ypad
GtkImage:xalign/yalign/xpad/ypad/stock
GtkButton:use-stock
and add icon to the 'Insert' button
> pluma-time-dialog.ui plugin: avoid deprecated:

- pluma/pluma-io-error-message-area.c
easy to test, just type in terminal:
`pluma ~`
and see the cancel button:
> error-message-area: avoid 'gtk_info_bar_new_with_buttons' with stock id

- plugins/filebrowser/pluma-file-browser-widget.c
- pluma/pluma-utils.c
- pluma/pluma-utils.h
gtk_image_menu_item_new_with_label
gtk_image_menu_item_set_image
> pluma-file-browser-widget.c: avoid deprecated GtkImageMenuItem

- pluma/pluma-view.c
The issue: right click here:
The expected:
Sometimes right click here doesn't show the item, just right click some times, seems it needs two right clicks to show it
In the tests: make sure you can't reproduce the issues https://github.com/mate-desktop/pluma/issues/215 , https://github.com/mate-desktop/pluma/issues/250 and https://github.com/mate-desktop/pluma/issues/256
> pluma-view.c: Fix: GtkCheckMenuItem "Display line numbers" improved

- pluma/pluma-notebook.c
- pluma/pluma-tab-label.c
Fixes https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=898637
I can't reproduce the debian bug, but reporter says this PR fixes the problem
In the tests, make sure the PR https://github.com/mate-desktop/pluma/pull/276 is working as before
> Fix: Pluma crashes with mouse wheel over a tab

- pluma/pluma-notebook.c
Fixes https://github.com/mate-desktop/pluma/issues/331
> pluma-notebook: avoid new file with double click in forward arrow button

- data/org.mate.pluma.gschema.xml.in
- pluma/pluma-window.c
If true the gsettings key "ctrl-tab-switch-tabs" into "org.mate.pluma"
Closes https://github.com/mate-desktop/pluma/issues/211
We have since a long time ago the PRs https://github.com/mate-desktop/pluma/pull/243 and https://github.com/mate-desktop/pluma/pull/242 with no news, and I like this feature, so, I decide to open this alternative PR.
We have the choice with the gsettings key.
> add the abbility to switch tabs using [ctrl+tab] and [ctrl+shift+tab]

- pluma/pluma-view.c
how to test:
go to `system -> preferences -> look and feel -> appearance -> fonts ->` change the `application font` to a `bold` or `itailc` font:
I think this is an accessibility fix
> pluma-view: Fix bold and italic fonts in menus

- plugins/sort/pluma-sort-plugin.c
Fixes https://github.com/mate-desktop/pluma/issues/153
> pluma-sort-plugin: avoid extra empty line

- pluma/dialogs/pluma-close-confirmation-dialog.c
Fixes https://github.com/mate-desktop/pluma/issues/356
> close-confirmation-dialog: Fix: don't resize the dialog unexpectedly

- pluma/dialogs/pluma-close-confirmation-dialog.c
how to test: just open multiple files to force the dialog and see the size:
Now resizable if it has vertical scrollbar, and the max height of the dialog is the 50% of the height of monitor (I can increase it if you like more).
> make the 'close confirmation dialog' bigger with multiple files

- pluma/pluma-document.c
In the commit https://github.com/mate-desktop/pluma/commit/4a74dc65ffb89e0ef391cdf1f0d4c07cb1d20889
The line `bom = g_strdup_printf ("%s%c", bom, c);` is called three times, but freed one time
https://github.com/mate-desktop/pluma/commit/4a74dc65ffb89e0ef391cdf1f0d4c07cb1d20889#diff-f46f2cae08ed2899ec953fd47b56976eR684
so, I did little changes to make sure there is no memory leaks.
> pluma-document: fix possible memory leak

- pluma/pluma-window.c
'g_strconcat' needs to be freed
How to test: just check if <kbd>ctrl</kbd><kbd>+</kbd> and <kbd>ctrl</kbd><kbd>-</kbd>  to change the font size works as before
> pluma-window: Fix memory leaks

- pluma/pluma-utils.c
'g_strconcat' needs to be freed
> pluma-utils: Fix memory leak

- plugins/snippets/snippets/Manager.py
addresses #391.
You see I moved the code to get the window size to before the point where it's destroyed destroyed.
I could have done it the other way - move the destroyed bit to after the window size operations. But moving where something is destroyed seemed more dangerous than just moving something about the default window size, especially as I don't know the structure of the code.
> addresses #391 - gets snippet window size before destroying it

- help/C/index.docbook
Open Location menu item is inaccessible, and mate-vs is deprecated.
To open a remote file you should connect to server first by using
Open File dialog. Next, select Other Locations from left pane, and
Connect to server.
> remove deprecated help section: Opening a File from a URI

- help/C/index.docbook
Example of generated file:
**help/pluma.pot before:**
msgid "To report a bug or make a suggestion regarding the &lt;application&gt;pluma&lt;/application&gt; application or this manual, follow the directions in the &lt;ulink url=\"help:mate-user-guide/feedback\" type=\"help\"&gt;MATE Feedback Page&lt;/ulink&gt;."
msgstr ""
**help/pluma.pot after:**
msgid "MATE Feedback Page"
msgstr ""
msgid "To report a bug or make a suggestion regarding the <application>pluma</application> application or this manual, follow the directions in the <_:ulink-1/>."
msgstr ""
> remove type & url attr of ulink in translation

- configure.ac
- plugins/spell/pluma-spell-checker.c
The enchant on Archlinux is 2.2.3-2, that include enchant-2.pc.
This commit first check enchant-2, then check enchant.
Here can see the file list of enchant on archlinux:
https://www.archlinux.org/packages/extra/x86_64/enchant/
```
usr/lib/libenchant-2.so
usr/lib/libenchant-2.so.2
usr/lib/libenchant-2.so.2.2.3
usr/lib/pkgconfig/
usr/lib/pkgconfig/enchant-2.pc
```
> Fix build fail on Archlinux

- help/C/index.docbook
- help/C/legal.xml
- help/pluma.pot
To upgrade the manual:
sudo dnf install -y docbook5-schemas
xsltproc --output index-new.docbook /usr/share/xml/docbook5/stylesheet/upgrade/db4-upgrade.xsl index.docbook
xsltproc --output legal-new.xml /usr/share/xml/docbook5/stylesheet/upgrade/db4-upgrade.xsl legal.xml
To validate the manual:
xmllint --noout --relaxng /usr/share/xml/docbook5/schema/rng/5.0/docbook.rng help/C/index.docbook
jing /usr/share/xml/docbook5/schema/rng/5.0/docbook.rng help/C/index.docbook
yelp-check validate help/C/index.docbook
To view the manual:
yelp file:///full_path/index.docbook
Note: docbook5-schemas should be installed in your system in order to view the manual (DEPENDENCY)
> Upgrade the manual to docbook 5.0

- help/C/index.docbook
Yelp viewer can't open cross-references to other parts of
the manual using link linkend.
> Help: replace link linkend with xref linkend

- help/C/index.docbook
With this I have also removed how we can install third-party plugins... we aren't offering that any more are we?
> remove live.gnome from plugins section

- plugins/quickopen/quickopen/__init__.py
- plugins/quickopen/quickopen/popup.py
- plugins/quickopen/quickopen/virtualdirs.py
- plugins/quickopen/quickopen/windowhelper.py
This rewrites the plugin in Python 3, while retaining Python 2 compatibility.
In addition, some bugs are fixed and the Gtk-3 compatibility is improved (mainly regarding widget deprecation).
> quickopen plugin: change code for Python 2 & 3 compatibility.

- configure.ac
- plugins/pythonconsole/Makefile.am
- plugins/pythonconsole/org.mate.pluma.plugins.pythonconsole.gschema.xml.in
- plugins/pythonconsole/pythonconsole/__init__.py
- plugins/pythonconsole/pythonconsole/config.py
- plugins/pythonconsole/pythonconsole/config.ui
- plugins/pythonconsole/pythonconsole/console.py
This rewrites the plugin in Python 3, while retaining Python 2 compatibility.
In addition, some bugs are fixed and the Gtk-3 compatibility is improved (mainly regarding UI and widget deprecation). The mateconf parameters have been replaced by GSettings.
> pythonconsole plugin: change source code for Python 2 & 3 compatibility.

- plugins/externaltools/tools/__init__.py
- plugins/externaltools/tools/capture.py
- plugins/externaltools/tools/functions.py
- plugins/externaltools/tools/library.py
- plugins/externaltools/tools/manager.py
- plugins/externaltools/tools/outputpanel.py
- plugins/externaltools/tools/outputpanel.ui
- plugins/externaltools/tools/tools.ui
This rewrites the plugin in Python 3, while retaining Python 2 compatibility.
In addition, some bugs are fixed and the Gtk-3 compatibility is improved (mainly regarding UI and widget deprecation).
> externaltools plugin: change code for Python 2 & 3 compatibility.

- plugins/snippets/snippets/Completion.py
- plugins/snippets/snippets/Document.py
- plugins/snippets/snippets/Exporter.py
- plugins/snippets/snippets/Helper.py
- plugins/snippets/snippets/Importer.py
- plugins/snippets/snippets/LanguageManager.py
- plugins/snippets/snippets/Library.py
- plugins/snippets/snippets/Manager.py
- plugins/snippets/snippets/Parser.py
- plugins/snippets/snippets/Placeholder.py
- plugins/snippets/snippets/Snippet.py
- plugins/snippets/snippets/WindowHelper.py
- plugins/snippets/snippets/__init__.py
- plugins/snippets/snippets/snippets.ui
This rewrites the plugin in Python 3, while retaining Python 2 compatibility.
In addition, some bugs are fixed and the Gtk-3 compatibility is improved (mainly regarding UI and widget deprecation).
> snippets plugin: change code for Python 2 & 3 compatibility

- configure.ac
- plugins/externaltools/externaltools.plugin.desktop.in
- plugins/pythonconsole/pythonconsole.plugin.desktop.in
- plugins/quickopen/quickopen.plugin.desktop.in
- plugins/snippets/snippets.plugin.desktop.in
- pluma/pluma-plugins-engine.c
Now that Python plugins have been updated to Python 3 compatible code, this PR can be merged to switch the whole Pluma package to use Python 3.
> Switch to Python 3

- README
- data/pluma.appdata.xml.in
- plugins/changecase/changecase.plugin.desktop.in
- plugins/externaltools/externaltools.plugin.desktop.in
- plugins/filebrowser/filebrowser.plugin.desktop.in
- plugins/modelines/modelines.plugin.desktop.in
- plugins/pythonconsole/pythonconsole.plugin.desktop.in
- plugins/quickopen/quickopen.plugin.desktop.in
- plugins/snippets/snippets.plugin.desktop.in
- plugins/sort/sort.plugin.desktop.in
- plugins/spell/spell.plugin.desktop.in
- plugins/taglist/taglist.plugin.desktop.in
- plugins/time/time.plugin.desktop.in
- plugins/trailsave/trailsave.plugin.desktop.in
- tools/plugin_template/pluma-plugin.desktop.in
Now the official web site is https://mate-desktop.org/.
> Change url project's website

- pluma/pluma-print-preview.c
based in gedit commit:
https://gitlab.gnome.org/GNOME/gedit/commit/e30939812fcf884d031757fb3cc2a8383f3ce21f
Fixes Clang analyzer warning:
```
pluma-print-preview.c:743:24: warning: identical expressions on both sides of logical operator
if (priv->tile_h <= 0 || priv->tile_h <= 0)
~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~
```
Fixes cppcheck warning:
`[pluma/pluma-print-preview.c:743]: (style) Same expression on both sides of '||'.`
> pluma-print-preview: Fix warning: identical expressions

- data/org.mate.pluma.gschema.xml.in
- pluma/dialogs/pluma-preferences-dialog.c
- pluma/dialogs/pluma-preferences-dialog.ui
- pluma/pluma-prefs-manager-app.c
- pluma/pluma-prefs-manager.c
- pluma/pluma-prefs-manager.h
- pluma/pluma-view.c
- pluma/pluma-view.h
This pull request allows to draw spaces, tabs, newlines and nbsp in Pluma. This capability is useful when you want to control if spaces or tab are used.
This pull request consists of two commits: the first one allow to control the drawing of these entities via gsettings:
- spaces (org.mate.pluma.enable-space-drawer-space)
- tabs (org.mate.pluma.enable-space-drawer-tab)
- newlines (org.mate.pluma.enable-space-drawer-newline)
- not blank space (org.mate.pluma.enable-space-drawer-nbsp)
The second commits allow to (un)set these options in the preferences dialog ('Editor' tab)
Please merge.
BR
G.Baroncelli <kreijack@inwind.it>
> Draw spaces, tabs, newlines and nbsp

- tests/smart-converter.c
```
Fixes clang analyzer warnings:
smart-converter.c:108:8: warning: Potential leak of memory pointed to by 'out'
if (!care_about_error)
^~~~~~~~~~~~~~~~
smart-converter.c:337:7: warning: Potential leak of memory pointed to by 'aux'
aux2 = do_test (aux, NULL, encs, aux_len, &guessed);
~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
smart-converter.c:339:12: warning: Potential leak of memory pointed to by 'aux2'
g_assert (guessed == pluma_encoding_get_from_charset ("UTF-16"));
^~~~~~~
```
> smart-converter: Fix memory leaks

- pluma/pluma-document.c
Fixes clang analyzer warning:
```
pluma-document.c:682:14: warning: The left operand of '==' is a garbage value
if ((bom[0] == '\357') &&
~~~~~~ ^
```
In the tests, make sure you can't reproduce the issue https://github.com/mate-desktop/pluma/issues/301
> pluma-document: avoid garbarge value in 'file_with_bom' function

- pluma/pluma-window.c
When setting the custom pluma window state we override the class method,
but never defer back to the parent class method. This means that window
states like backdrop are never set on Pluma.
> window: Do not override GdkWindowState

- plugins/README.md
Removing the note regarding the disabled Python 2 plugins, since we now have compatibility with Python 3.
> remove note for disabled Python 2 plugins

- plugins/filebrowser/pluma-file-bookmarks-store.c
- plugins/filebrowser/pluma-file-browser-messages.c
- plugins/filebrowser/pluma-file-browser-store.c
- plugins/filebrowser/pluma-file-browser-view.c
- plugins/filebrowser/pluma-file-browser-widget.c
- plugins/spell/pluma-spell-checker-dialog.c
- pluma/pluma-commands-file.c
- pluma/pluma-history-entry.c
- pluma/pluma-message-bus.c
- pluma/pluma-prefs-manager.c
- pluma/pluma-utils.c
- pluma/pluma-window.c
- pluma/pluma.c
```
pluma.c:131:30: warning: cast between incompatible function types from ‘void (*)(void *)’ to ‘void (*)(void *, void *)’ [-Wcast-function-type]
131 |  g_slist_foreach (file_list, (GFunc) g_object_unref, NULL);
|                              ^
--
pluma-commands-file.c:299:26: warning: cast between incompatible function types from ‘void (*)(void *)’ to ‘void (*)(void *, void *)’ [-Wcast-function-type]
299 |  g_slist_foreach (files, (GFunc) g_object_unref, NULL);
|                          ^
--
pluma-commands-file.c:436:26: warning: cast between incompatible function types from ‘void (*)(void *)’ to ‘void (*)(void *, void *)’ [-Wcast-function-type]
436 |  g_slist_foreach (files, (GFunc) g_object_unref, NULL);
|                          ^
--
pluma-history-entry.c:229:35: warning: cast …
```
> Remove warnings: cast between incompatible function types

- help/C/index.docbook
Test
```
$ yelp help:pluma/pluma-shortcutkeys
```
> help: Remove Open Location from shortcut keys table

- help/C/index.docbook
Test
```shell
$ yelp help:pluma/pluma-open-file
```
Screenshot
> help: Add tip about how to show location entry on Open File dialog

- help/C/index.docbook
Test:
```
$ yelp help:pluma/pluma-find-text
```
Closes #538
> help: add a link to syntax and semantics of regex

- pluma/pluma-utils.c
Test: search `^\d{2}\.\w{3}+.*` in te text below:
```
11 aa 222
11.aaa 222
11 aaa 222
11.aaa 222
11
11.aaa 222
```
Result: found the even lines
Closes #541
> pluma-utils: Enable multiline mode on regex search

- pluma/pluma.c
Fixes #194 and according warnings `(pluma:32085): Gtk-CRITICAL **: 22:14:17.094: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar`
> pluma.c: set PlumaWindow size-request (min-size) to 250x250

- pluma/pluma-app.c
- pluma/pluma-utils.c
- pluma/pluma.c
- pluma/smclient/eggdesktopfile.c
See https://developer.gnome.org/gdk3/stable/gdk3-Wayland-Interaction.html for details.
I have been playing with pluma (master) and weston (8.0.0-1) in a vm with Ubuntu MATE 20.04 lately. Although I don't know neither pluma nor weston a lot, it seems to work for me.
Test: install weston, launch weston in terminal or logout and go into a proper weston session (for me on debian stable and weston 5.0.0-3 I got a black screen) and compile and launch pluma.
> wayland: add  guard backend-specific calls by an ifdef

- pluma/pluma-encodings-combo-box.c
- pluma/pluma-utils.c
- tests/document-saver.c
Test:
```
$ CFLAGS="-Wunused-macros" ./autogen.sh --prefix=/usr && LANG=en_US.UTF-8 make &> make.log
$ grep -v marshal make.log | grep -v EGG | grep -A 2 unused-macros
<cut>
--
pluma-encodings-combo-box.c:43: warning: macro "ENCODING_KEY" is not used [-Wunused-macros]
43 | #define ENCODING_KEY "Enconding"
| 
--
pluma-utils.c:60: warning: macro "STDIN_DELAY_MICROSECONDS" is not used [-Wunused-macros]
60 | #define STDIN_DELAY_MICROSECONDS 100000
| 
--
document-saver.c:45: warning: macro "UNOWNED_REMOTE_DIRECTORY" is not used [-Wunused-macros]
45 | #define UNOWNED_REMOTE_DIRECTORY "sftp://localhost/tmp/pluma-document-saver-unowned"
| 
```
> Remove unused macros

- plugins/filebrowser/pluma-file-browser-widget.c
- pluma/pluma-ui.h
```
--
pluma-ui.h:47:2: warning: missing initializer for field 'accelerator' of 'GtkActionEntry' {aka 'const struct _GtkActionEntry'} [-Wmissing-field-initializers]
47 |  { "File", NULL, N_("_File") },
|  ^
--
pluma-ui.h:48:2: warning: missing initializer for field 'accelerator' of 'GtkActionEntry' {aka 'const struct _GtkActionEntry'} [-Wmissing-field-initializers]
48 |  { "Edit", NULL, N_("_Edit") },
|  ^
--
pluma-ui.h:49:2: warning: missing initializer for field 'accelerator' of 'GtkActionEntry' {aka 'const struct _GtkActionEntry'} [-Wmissing-field-initializers]
49 |  { "View", NULL, N_("_View") },
|  ^
--
pluma-ui.h:50:2: warning: missing initializer for field 'accelerator' of 'GtkActionEntry' {aka 'const struct _GtkActionEntry'} [-Wmissing-field-initializers]
50 |  { "Search", NULL, …
```
> Remove -Wmissing-field-initializers warnings

- pluma/pluma-document.c
Test: Create a new document, without saving the new document, select a highlight mode
```
(pluma:84684): GLib-GIO-CRITICAL **: 22:56:46.725: g_file_get_path: assertion 'G_IS_FILE (file)' failed
fopen: Bad address
```
> pluma-document: Fix warning assertion 'G_IS_FILE (file)' failed

- plugins/time/pluma-time-plugin.c
based on https://github.com/GNOME/gedit/commit/121f02a3ea066565eeae5dd42868f822ecce4924 and https://github.com/GNOME/gedit/commit/ef65fda074d58296b8c919f64744e48a1e610123
> pluma-time-plugin: Use g_date_time_format

- pluma/pluma-document.c
It's no longer necessary to disable the highlighting for UTF-8 files with BOM.
This restriction was added on #357
Test: There is no segment violation when opening a file with BOM
```shell
$ wget https://gitlab.gnome.org/GNOME/gtksourceview/uploads/7a547f881776e85c92e3732d75f1087f/wp-config.php
$ pluma wp-config.php
```
See https://gitlab.gnome.org/GNOME/gtksourceview/-/commit/54e48e9c
> pluma-document: highlighting for BOM was fixed on gtksourceview 3.24.11

- docs/reference/Makefile.am
Fix make distcheck failed on archlinux:
```
make[2]: Leaving directory '/rootdir/pluma-1.25.0/_build/sub'
rm -f config.status config.cache config.log configure.lineno config.status.lineno
rm -f Makefile
ERROR: files left in build directory after distclean:
./docs/reference/pluma.actions
make[1]: *** [Makefile:812: distcleancheck] Error 1
make[1]: Leaving directory '/rootdir/pluma-1.25.0/_build/sub'
make: *** [Makefile:741: distcheck] Error 1
!!! ERROR: run command [docker exec -t pluma-archlinux-build /rootdir/after_scripts].
```
> travis: fix build error on archlinux

- pluma/Makefile.am
- pluma/pluma-pango.c
- pluma/pluma-pango.h
- pluma/pluma-view.c
Fixes issue #525 by setting the textview font with css without also setting
the font for the labels. Changes based on gedit and gtk/gtkfontbutton.c.
> pluma-view: Fix incorrect interface font - 1.24 branch

- pluma/pluma-print-job.c
Test:
open `File->Print`, then switch to `Text Editor ` and see that `Text Wrapping` options have an effect now.
> fix printing wrap mode

- pluma/Makefile.am
- pluma/pluma-app-activatable.c
- pluma/pluma-app-activatable.h
- pluma/pluma-app.c
- pluma/pluma-view-activatable.c
- pluma/pluma-view-activatable.h
- pluma/pluma-view.c
- pluma/pluma-window-activatable.c
- pluma/pluma-window-activatable.h
- pluma/pluma-window.c
These interfaces are for extensions that should be activated against a window/app/view.
Backport from
- https://gitlab.gnome.org/GNOME/gedit/-/commit/4fe7161560941ae1aa42165ff4d71121ad6f67b9
- https://gitlab.gnome.org/GNOME/gedit/-/commit/56a790a6851ebc98766cc4aca27cb32dde1b41bf
- https://gitlab.gnome.org/GNOME/gedit/-/commit/210ed41e48988646203fc94eba19ce94657821cd
For indentation please review the "tab to spaces" commit.
>  Introduce PlumaWindowActivatable, PlumaAppActivatable, PlumaViewActivatable

- pluma/pluma-file-chooser-dialog.c
- pluma/pluma-tab.c
Test:
```
$ cppcheck --enable=all --quiet . &> cppcheck.log && grep shadowVariable cppcheck.log
pluma/pluma-file-chooser-dialog.c:303:12: style: Local variable 'mime_types' shadows outer variable [shadowVariable]
pluma/pluma-tab.c:998:15: style: Local variable 'emsg' shadows outer variable [shadowVariable]
```
> cppcheck warning: Local variable shadows outer variable

- pluma/pluma-window.c
> pluma-window: unused variable ‘ui_file’ [-Wunused-variable]

- plugins/filebrowser/pluma-file-browser-widget.c
Test
```
$ cppcheck --enable=all --quiet . &> cppcheck.log && grep shadowArgument cppcheck.log
plugins/filebrowser/pluma-file-browser-widget.c:1538:14: style: Local variable 'icon' shadows outer argument [shadowArgument]
```
> cppcheck warning: Local variable 'icon' shadows outer argument

- plugins/taglist/pluma-taglist-plugin-panel.c
Test:
```
$ cppcheck --enable=all --quiet . &> cppcheck.log && grep unsignedLessThanZero cppcheck.log 
plugins/taglist/pluma-taglist-plugin-panel.c:419:51: style: Checking if unsigned expression 'strlen(group_name)' is less than zero. [unsignedLessThanZero]
```
> cppcheck warning: Checking if unsigned expression is less than zero

- plugins/sort/pluma-sort-plugin.c
- plugins/sort/sort.ui
This allows the user to undo a sorting operation.
Further this commit simplifies the code and updates the ui file.
see:
https://developer.gnome.org/gtksourceview/stable/GtkSourceBuffer.html#gtk-source-buffer-sort-lines 
and
https://gitlab.gnome.org/GNOME/gedit/-/commit/bd811c40fd48433859ae2ae5e9a97d74633ab453
> sort plugin: Port sort plugin to the new GtkSourceView api.

- plugins/taglist/pluma-taglist-plugin-parser.c
```
pluma-taglist-plugin-parser.c:290:28: warning: declaration of ‘taglist’ shadows a global declaration [-Wshadow]
290 | lookup_best_lang (TagList *taglist, const gchar *filename,
|                   ~~~~~~~~~^~~~~~~
pluma-taglist-plugin-parser.c:48:10: note: shadowed declaration is here
48 | TagList* taglist = NULL;
|          ^~~~~~~
```
> warning: declaration of ‘taglist’ shadows a global declaration

- data/pluma-bugreport.sh.in
- plugins/externaltools/data/build.tool.in
- plugins/externaltools/data/open-terminal-here.tool.in
- plugins/externaltools/data/remove-trailing-spaces.tool.in
- plugins/externaltools/data/run-command.tool.in
- plugins/externaltools/data/search-recursive.tool.in
- plugins/externaltools/data/switch-c.tool.in
- mangling shebang warnings
- ambiguous python shebang error
From fedora build server with pluma-1.24.2
https://koji.fedoraproject.org/koji/getfile?taskID=64704645&volume=DEFAULT&name=build.log&offset=-4000
```
+ /usr/lib/rpm/redhat/brp-mangle-shebangs
mangling shebang in /usr/share/pluma/plugins/externaltools/tools/build from /bin/sh to #!/usr/bin/sh
mangling shebang in /usr/share/pluma/plugins/externaltools/tools/open-terminal-here from /bin/sh to #!/usr/bin/sh
mangling shebang in /usr/share/pluma/plugins/externaltools/tools/remove-trailing-spaces from /bin/sh to #!/usr/bin/sh
mangling shebang in /usr/share/pluma/plugins/externaltools/tools/run-command from /bin/sh to #!/usr/bin/sh
mangling shebang in /usr/share/pluma/plugins/externaltools/tools/search-recursive from /bin/bash to …
```
> build: fix shebangs

- pluma/pluma-view.c
see https://gitlab.gnome.org/GNOME/gedit/-/commit/aed206a36a561a60fd06db66182f91ad8d666992. In this commit it was deleted as well. The activation of the extensions takes place in `pluma_view_realize` (l. 2316) by calling 
```
peas_extension_set_foreach (view->priv->extensions,
(PeasExtensionSetForeachFunc) extension_added,
view);
```
This should fix the problem exposed by https://github.com/mate-desktop/pluma-plugins/pull/31.
> Fix double activation of extensions

- pluma/pluma-plugins-engine.c
```
LeakSanitizer: detected memory leaks
Direct leak of 64 byte(s) in 1 object(s) allocated from:
#0 0x7f93b66cfcb8 in __interceptor_realloc (/lib64/libasan.so.6+0xaecb8)
#1 0x7f93b52a4c97 in g_realloc ../glib/gmem.c:171
#2 0x7f93b52cbe42 in g_string_maybe_expand ../glib/gstring.c:102
#3 0x7f93b52cc6b7 in g_string_insert_len ../glib/gstring.c:486
#4 0x7f93b52cc386 in g_string_append ../glib/gstring.c:549
#5 0x7f93b527e63f in g_build_path_va ../glib/gfileutils.c:1969
#6 0x7f93b527e92b in g_build_filename_va ../glib/gfileutils.c:2192
#7 0x7f93b527eac8 in g_build_filename ../glib/gfileutils.c:2274
#8 0x4317c3 in pluma_dirs_get_user_plugins_dir /home/robert/builddir.gcc/pluma/pluma/pluma-dirs.c:53
#9 0x44fc39 in pluma_plugins_engine_init …
```
> pluma-plugins-engine: fix memory leak

- pluma/pluma-commands-search.c
```
CC=clang CFLAGS="-g -O0 -Wconversion -Wunused-macros -Wunused-parameter" ./autogen.sh --prefix=/usr --enable-debug  --enable-compile-warnings=maximum && make &> make.log && sudo make install
```
Fix build warning:
```
pluma-commands-search.c:401:28: warning: implicit conversion from enumeration type 'GtkTextSearchFlags' to different enumeration type 'GRegexCompileFlags' [-Wenum-conversion]
match_case ? 0 : GTK_TEXT_SEARCH_CASE_INSENSITIVE ,
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Test: find and replace a regex with or without match case.
> pluma-commands-search: fix warning -Wenum-conversion

- plugins/externaltools/data/build.tool.in
- plugins/externaltools/data/open-terminal-here.tool.in
- plugins/externaltools/data/remove-trailing-spaces.tool.in
- plugins/externaltools/data/run-command.tool.in
- plugins/externaltools/data/search-recursive.tool.in
See [issue 640](https://github.com/mate-desktop/pluma/issues/640) for discussion on reverting /usr/bin/sh shebangs.
Also fix search-recursive to be more POSIX compliant.  Remove bashishms and non-POSIX expr(1) usage.  And make the script simpler and more efficient at the same time.
> revert /usr/bin/sh shebangs + make search-recursive POSIX compliant

- pluma/pluma-encodings-combo-box.c
```
git submodule init
git submodule update --recursive --remote
CFLAGS="-g -O0 -Wconversion -Wunused-macros -Wunused-parameter" CC=clang ./autogen.sh --prefix=/usr --enable-compile-warnings=maximum && make &> make.log
```
```
pluma-encodings-combo-box.c:90:29: warning: implicit conversion changes signedness: 'gboolean' (aka 'int') to 'guint' (aka 'unsigned int') [-Wsign-conversion]
combo->priv->save_mode = g_value_get_boolean (value);
~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```
> pluma-encodings-combo-box: implicit conversion changes signedness

- pluma/pluma.c
```
pluma.c:126:7: warning: missing field 'short_name' initializer [-Wmissing-field-initializers]
{NULL}
^
```
> pluma: fix build warning about missing field initializer

- pluma/pluma-metadata-manager.c
Test:
1. disable gvfs metadata using `--disable-gvfs-metadata`
```
./autogen.sh --prefix=/usr --enable-debug --disable-gvfs-metadata && make && sudo make install
```
2. open a file in pluma, click anywhere in the opened file, and close pluma
3. check the value of atime in ~/.cache/pluma/pluma-metadata.xml
```
<?xml version="1.0"?>
<metadata>
<document uri="file:///home/robert/backup.sh" atime="1637781907">
<entry key="metadata::pluma-position" value="839"/>
</document>
</metadata>
```
> pluma-metadata-manager: remove time.h

- pluma/pluma-window.c
Closes #664
The size of tempfont was one byte too short, so strcpy performed an out-of-bounds write when writing the terminating 0. This lead to segfault when D_FORTIFY_SOURCE=3 compiler flag was turned on.
Fix tested on openSUSE Tumbleweed.
> Fix out-of-bounds write

- pluma/pluma-pango.c
1. If the font-family'value is Chinese or any non ASCII characters, the GTK CSS parser will produce a warning message: "Theme parsing error: <data>:1:24: Expected a string.". That is, the GTK CSS parser can not process Chinese or non ASCII characters correctly.
2. So, we should add quotes before and after font-family's value.
3. GTK4 has good support for non ASCII characters.
> Add quotes before and after font-family's value

- pluma/pluma-app.c
- pluma/pluma-window.c
- pluma/pluma-window.h
These two commits improve the window size behaviour.
The window currently grows bigger and bigger, as it is using the window allocation as the saved size, which isn't recommended per the gtk documentation.
In addition, the maximized window saving behaviour is improved by saving the unmaximized size, which is a more consistent user experience.
> Improve window behaviour
