- data/pluma.1
taken from Debian patch 2001_fix-man-page-errors.patch
@sunweaver: so you can remove the patch after this PR is accepted
> removed erroneous line from manpage

- pluma/pluma-print-preview.c
adapted from
https://git.gnome.org/browse/gedit/commit?id=9453de86abac1cf1bf4702091944301ac800bdef
fixes https://github.com/mate-desktop/pluma/issues/47
> GTK+3: work with "draw" signal instead of "expose" in print preview

- plugins/filebrowser/pluma-file-browser-view.c
- plugins/filebrowser/pluma-file-browser-widget.c
- pluma/pluma-tab.c
- Gtk+-3.16: gdk_cursor_new --> gdk_cursor_new_for_display
- GTK3: gdk_cursor_unref --> g_object_unref
> GTK3: replace reprecatated gdk_cursor functions

- configure.ac
- plugins/Makefile.am
- plugins/snippets/Makefile.am
- plugins/snippets/snippets.plugin.desktop.in
- plugins/snippets/snippets/Completion.py
- plugins/snippets/snippets/Document.py
- plugins/snippets/snippets/Exporter.py
- plugins/snippets/snippets/Helper.py
- plugins/snippets/snippets/Importer.py
- plugins/snippets/snippets/LanguageManager.py
- plugins/snippets/snippets/Library.py
- plugins/snippets/snippets/Manager.py
- plugins/snippets/snippets/Placeholder.py
- plugins/snippets/snippets/Snippet.py
- plugins/snippets/snippets/WindowHelper.py
- plugins/snippets/snippets/__init__.py
- plugins/snippets/snippets/snippets.ui
- po/POTFILES.in
- po/POTFILES.skip
Use ```Tools -> Manage Snippets...``` menu item to open Snippets Manager. You can check the available snippets for various languages there.
How to test it: open some file with code, type one of supported snippets and press Tab.
Example: type ```for``` in C file and you should get this:
Then you can change the values in placeholders to something else. Use Tab and Shift-Tab to move between placeholders.
> port snippets plugin to gi and libpeas

- pluma/pluma-view.c
> Fix: the tab closes unexpectedly with middle click under line numbers

- pluma/pluma-notebook.c
> Fix: pluma closes tabs unexpectedly with middle click

- configure.ac
- plugins/filebrowser/pluma-file-browser-store.c
- plugins/filebrowser/pluma-file-browser-view.c
- pluma/pluma-io-error-message-area.c
- pluma/pluma-notebook.c
- pluma/pluma-progress-message-area.c
- pluma/pluma-tab.c
- pluma/pluma-view.c
> deprecations and warnings

- pluma/pluma-window.c
this prevent us the write to disk uselessly
Closes #199 
we can see this same behavior in geany
> disable the abbility to save the document if it has no changes

- plugins/filebrowser/pluma-file-browser-widget.c
- pluma/pluma-help.c
> Dev gtk show uri

- data/org.mate.pluma.gschema.xml.in
- pluma/pluma-notebook.c
- pluma/pluma-window.c
Fixes #23 
I began the job with https://github.com/mate-desktop/pluma/pull/226 but I can't reopen the PR
This is an old request by some users
> Hide tabs if we are using the sidebar

- pluma/pluma-tab.c
Fixes https://github.com/mate-desktop/pluma/issues/230
@monsta please test
> don't request to save documents with no changes

- data/org.mate.pluma.gschema.xml.in
- pluma/pluma-tab.c
Closes https://github.com/mate-desktop/pluma/issues/112
> add gsettings key: Show save confirmation if the files have changes

- pluma/pluma-view.c
Fixes https://github.com/mate-desktop/pluma/issues/256
> Fix: pluma closes tabs unexpectedly with [right+middle] click

- pluma/pluma-app.c
adaptation of the PR https://github.com/mate-desktop/pluma/pull/262 to 1.18
> [1.18] make sure pluma open in the same window of the workspace

- plugins/externaltools/tools/__init__.py
Fixes https://github.com/mate-desktop/pluma/pull/273#issuecomment-364460525
@raveit65 please test
> Fix warning with external tools plugin

- plugins/pythonconsole/pythonconsole/config.ui
the expected: the same look and behavior like before
> python console: config.ui: avoid GtkButton:use-stock

- plugins/time/pluma-time-setup-dialog.ui
GtkVBox
GtkHBox
GtkLabel:xpad/ypad
GtkButton:use-stock
> pluma-time-setup-dialog.ui plugin: avoid deprecated:

- plugins/sort/sort.ui
GtkVBox
GtkHBox
GtkLabel:xpad/ypad
GtkImage:xpad/ypad/xalign/yalign/stock
GtkButton:use-stock
> sort.ui plugin: avoid deprecated:

- plugins/time/pluma-time-plugin.c
I have no idea how to test this PR
> pluma-time-plugin.c: avoid 'gtk_dialog_new_with_buttons' with stock id

- pluma/pluma-notebook.c
gdk_pointer_is_grabbed
gdk_pointer_grab
gdk_pointer_ungrab
> pluma-notebook.c: avoid deprecated 'gdk_pointer_ ...' functions

- pluma/pluma-window.c
follow up for https://github.com/mate-desktop/pluma/pull/319
> use gtk_menu_popup_at_widget for GtkNotebook

- pluma/pluma-view.c
Fixes https://github.com/mate-desktop/pluma/issues/327
> pluma-view: Fix: unexpected behavior with dnd under line numbers

- pluma/pluma-view.c
culprit commit: https://github.com/mate-desktop/pluma/commit/310bfc249aac3dd80511d3dade14aa06f3d9769a (my fault)
Since that commit bold and italic fonts don't work
This is the fix
> pluma-view: Fix: Bold and Italic fonts don't work

- pluma/pluma-view.c
Closes https://github.com/mate-desktop/pluma/issues/349
> pluma-view: Fix: unexpectedly switch between tabs

- pluma/pluma-document.c
Fixes https://github.com/mate-desktop/pluma/issues/301
> pluma-document: Fix: don't crash using files with 'bom'

- pluma/pluma-view.c
Fixes https://github.com/mate-desktop/pluma/issues/179
> pluma-view: Fix: Don't loss the PRIMARY clipboard

- pluma/pluma-document.c
- pluma/pluma-utils.c
Fixes https://github.com/mate-desktop/pluma/issues/322
> Fix search backwards with regex

- pluma/pluma-app.c
- pluma/pluma-document.c
- pluma/pluma-message-type.c
- pluma/pluma-prefs-manager-app.h
- pluma/pluma-prefs-manager.h
- pluma/pluma-utils.c
> Gir and docs

- pluma/pluma-commands-help.c
> Add License button in About Pluma dialog

- .travis.yml
This PR maybe OK, but I found an issue when building pluma on archlinux, I will open a new PR to fix that.
> Enable Travis CI support

- help/C/index.docbook
- plugins/README.md
- plugins/changecase/README.md
- plugins/docinfo/README.md
- plugins/filebrowser/README.md
- plugins/modelines/README.md
- plugins/sort/README.md
- plugins/spell/README.md
- plugins/taglist/README.md
- plugins/time/README.md
- plugins/trailsave/README.md
Changes:
- Add README files to ``/plugins`` and inside each individual plugins directory.
- Add documentation for **trailsave** plugin in the user manual.
I've only added README files to the active plugins.
> Plugin phase one

- plugins/externaltools/tools/__init__.py
- plugins/externaltools/tools/capture.py
- plugins/externaltools/tools/functions.py
- plugins/externaltools/tools/library.py
- plugins/externaltools/tools/linkparsing.py
- plugins/externaltools/tools/manager.py
- plugins/externaltools/tools/outputpanel.py
- plugins/pythonconsole/pythonconsole/__init__.py
- plugins/quickopen/quickopen/__init__.py
- plugins/quickopen/quickopen/popup.py
- plugins/quickopen/quickopen/virtualdirs.py
- plugins/quickopen/quickopen/windowhelper.py
- plugins/snippets/snippets/Completion.py
- plugins/snippets/snippets/Document.py
- plugins/snippets/snippets/Exporter.py
- plugins/snippets/snippets/Helper.py
- plugins/snippets/snippets/Importer.py
- plugins/snippets/snippets/LanguageManager.py
- plugins/snippets/snippets/Library.py
- plugins/snippets/snippets/Manager.py
- plugins/snippets/snippets/Parser.py
- plugins/snippets/snippets/Placeholder.py
- plugins/snippets/snippets/Snippet.py
- plugins/snippets/snippets/SubstitutionParser.py
- plugins/snippets/snippets/WindowHelper.py
- plugins/snippets/snippets/__init__.py
- tools/generate-plugin.py
- tools/preprocessor.py
This is the first commit of https://github.com/mate-desktop/pluma/pull/425, as requested in the comments.
It only reindents Python code and strip trailing spaces. No code change thus still working with Python 2.
> Reindent all Python sources to ts=4. Strip trailing spaces.

- pluma/pluma-view.c
avoid static gboolean variable in function `pluma_override_font`
> pluma-view: avoid static gboolean variable

- data/org.mate.pluma.gschema.xml.in
- pluma/dialogs/pluma-preferences-dialog.ui
Draw is confusing for users. Changing to Show
> preferences: Change Draw to Show

- pluma/pluma-notebook.c
- pluma/pluma-tab.c
- pluma/pluma-view.c
- pluma/pluma-window.c
use Gsettings `'pluma_prefs_manager'` instead
> avoid to make new Gsettings variables

- data/org.mate.pluma.gschema.xml.in
Signed-off-by: zhangjialing <zhangjialing@loongson.cn>
> add gbk encoding to fix open no utf8 Simplified Chinese

- pluma/pluma-commands-help.c
> pluma-commands-help: expand the comment on about dialog

- pluma/dialogs/pluma-preferences-dialog.c
Fixes #501 and fixes #502.
GTK3 removed the ability to scroll over tabs. This commit re-implements this functionality, while still retaining the feature for GTK2 builds.
Regards.
> Add tab scrolling support for GTK3

- git.mk
> add git.mk to generate .gitignore

- pluma/dialogs/pluma-preferences-dialog.c
Based on:
- https://github.com/mate-desktop/mate-terminal/commit/8d2eb0898154f2624e2ae34039169f307a3411a5
- https://github.com/mate-desktop/mate-terminal/commit/622e2d1272bf2d7a99d147482ae6a51b0a77f188
> pluma-preferences-dialog: Refactor on_notebook_scroll_event

- pluma/pluma-window.c
see https://gitlab.gnome.org/GNOME/gedit/-/commit/b58abf733f508b3dc0358882929bef26ff61925c
> Use gtk_source_view_get_visual_column

- pluma/Makefile.am
- pluma/pluma-pango.c
- pluma/pluma-pango.h
- pluma/pluma-view.c
Based on
https://gitlab.gnome.org/GNOME/gedit/-/commit/100b91ee49feeaf848ff1486e952d27394fcbf74
and
https://gitlab.gnome.org/GNOME/gedit/-/merge_requests/100
> Fix issue #525 setting textview font css based on gedit and gtk/gtkfontbutton.c

- pluma/pluma-view.c
Test: right-click on line-numbers
> Fix line numbers menu: use g_settings_bind correctly

- help/C/index.docbook
- pluma/pluma-window.c
> add show/hide line-numbers shortcut (ctrl+y)

- help/C/index.docbook
> help: add indent shortcuts

- README.md
> README.md: configure options

- .build.yml
- README.md
- configure.ac
- data/pluma-bugreport.sh.in
- data/pluma.pc.in
- pluma/Makefile.am
- pluma/pluma-document.c
based on https://gitlab.gnome.org/GNOME/gtksourceview/-/commit/54e48e9c
further info https://developer.gnome.org/gtksourceview/stable/porting-guide-3-to-4.html
closes #618
> build: port to gtksourceview-4

- plugins/docinfo/pluma-docinfo-plugin.c
- plugins/externaltools/tools/__init__.py
- plugins/filebrowser/pluma-file-browser-plugin.c
- plugins/modelines/pluma-modeline-plugin.c
- plugins/pythonconsole/pythonconsole/__init__.py
- plugins/quickopen/quickopen/__init__.py
- plugins/snippets/snippets/__init__.py
- plugins/sort/pluma-sort-plugin.c
- plugins/spell/pluma-spell-plugin.c
- plugins/taglist/pluma-taglist-plugin.c
- plugins/time/pluma-time-plugin.c
- plugins/trailsave/pluma-trail-save-plugin.c
pluma-file-browser-plugin.c: rename "data" to "priv".
Do not merge before #615
> Port all plugins to use the window-construct property

- plugins/filebrowser/pluma-file-browser-plugin.c
Fixes #630 (cuplrit f4ed7690bff4021051f11fbe851b604d69caef2f)
> filebrowser-plugin: fix segfault on open-terminal action

- pluma/pluma-encodings-combo-box.c
* Fix #703
* Move initialization of the combo box into a constructor function as in gedit
> Show the default/current choice in filechooser Character Encoding combo box
